# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_array', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TestException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_request', models.IntegerField()),
                ('item_array_index', models.IntegerField()),
                ('exception_text', models.CharField(max_length=100)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='json_processor.InputData')),
            ],
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_request', models.IntegerField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='json_processor.InputData')),
            ],
        ),
    ]
