# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_processor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testexception',
            old_name='item_array_index',
            new_name='array_item_index',
        ),
    ]
