# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_processor', '0002_auto_20170929_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexception',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='testexception',
            name='test_request',
        ),
        migrations.AddField(
            model_name='testexception',
            name='test_info',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='json_processor.TestInfo'),
            preserve_default=False,
        ),
    ]
